name: mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.16+40

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Network
  dio: ^4.0.6
  connectivity_plus: ^2.3.0
  http: 
  geolocator: ^9.0.1
  vexana: ^2.8.1
  loader_overlay: ^2.0.7
  # State Management
  provider: ^6.0.2
  # Cache & Storage
  shared_preferences: ^2.0.13
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.1.0

  # Others
  easy_localization: ^3.0.0
  lottie: ^1.3.0
  flutter_svg: ^1.1.1
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
  mask_input_formatter: ^0.0.3
  auto_size_text: ^3.0.0
  device_info_plus: ^3.2.3
  package_info: ^2.0.0
  flutter_svg_provider: ^1.0.3 
  is_lock_screen: ^2.0.0
  shimmer: ^2.0.0
  flutter_multi_formatter: ^2.5.7
  screenshot: ^1.2.3
  share: ^2.0.4
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  money_input_formatter: ^2.0.0
  url_launcher: ^6.1.4
  flutter_spinkit: ^5.1.0
  yandex_mapkit: ^3.0.2
  permission_handler: ^9.2.0
  camera: ^0.9.8+1
  flutter_windowmanager: ^0.2.0
  # Firebase
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_performance: ^0.8.2+1
  firebase_analytics: ^9.3.0
  stack_trace: ^1.10.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/fonts/
    - assets/images/
    - assets/images/dialogs/
    - assets/images/biometric/
    - assets/images/bank_logo_png/
    - assets/icon/
    - assets/animations/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/SegoeUI.ttf
        - asset: assets/fonts/SegoeUI-Bold.ttf
        - asset: assets/fonts/SegoeUI-SemiBold.ttf
        - asset: assets/fonts/SegoeUI-Light.ttf
          style: normal
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
